* Renaming of sankey clusters

* Agriculture
replace originalsource = "Unknown" if originalsource == "?"
replace originalsource = "FAOSTAT" if originalsource == "FAO"
replace originalsource = "WB cluster" if originalsource == "WB/GFAR/SNV"
replace originalsource = "Europe cluster" if originalsource == "Defra"
replace originalsource = "WFP cluster" if originalsource == "WFP"
replace originalsource = "Europe cluster" if originalsource == "FRA"
replace originalsource = "Europe cluster" if originalsource == "EMEP"
replace originalsource = "UN cluster" if originalsource == "UN"
replace originalsource = "UN cluster" if originalsource == "ISRIC/UNEP"
replace originalsource = "WB cluster" if originalsource == "WB"
replace originalsource = "WB cluster" if originalsource == "WB/Brookings Institution"
replace originalsource = "IFAD Projects" if originalsource == "IFAD"
replace originalsource = "WB cluster" if originalsource == "WB/OECD"
replace originalsource = "WB cluster" if originalsource == "WB/FAO"
replace originalsource = "UN cluster" if originalsource == "ILO"
replace originalsource = "WHO cluster" if originalsource == "WHO/UNICEF"
replace originalsource = "UN cluster" if originalsource == "UN/WB/IMF/ADB"
replace originalsource = "UN cluster" if originalsource == "Based on ILO/WB"
replace originalsource = "UN cluster" if originalsource == "Based on ILO and National Statistics Offices"
replace originalsource = "UN cluster" if originalsource == "Based on ILO/WB ICP"
replace originalsource = "UN cluster" if originalsource == "Based on UN/World Urbanization Prospects"
replace originalsource = "Household Budget Surveys" if originalsource == "Household Budget Surveys/Living Standard Measurement Surveys/Others"
replace originalsource = "Key informants" if originalsource == "Community key informants/local traders"
replace originalsource = "National Census and Ministry reporting" if originalsource == "Trade and Official data"
replace originalsource = "FAOSTAT" if originalsource == "FAO questionnaire"
replace originalsource = "FAOSTAT" if originalsource == "FAO/CRU"
replace originalsource = "Other" if originalsource == "JMP"
replace originalsource = "Other" if originalsource == "GFED4/EC-JRC"
replace originalsource = "National Census and Ministry reporting" if originalsource == "National institutions"
replace originalsource = "National Census and Ministry reporting" if originalsource == "National authorities"
replace originalsource = "National Census and Ministry reporting" if originalsource == "Official government sources"
replace originalsource = "FAOSTAT" if originalsource == "FAO/WB/UNDP"
replace originalsource = "FAOSTAT" if originalsource == "FAO/EC-JRC/Wint and Robinson"
replace originalsource = "FAOSTAT" if originalsource == "FAO/UNSD/IEA"
replace originalsource = "FAOSTAT" if originalsource == "FAO/EC-JRC"
replace originalsource = "FAOSTAT" if originalsource == "FAO/GFED4/EC-JRC"
replace originalsource = "FAOSTAT" if originalsource == "FAO/IIASA"
replace originalsource = "FAOSTAT" if originalsource == "FAO/WB"

replace originalsource = "FAOSTAT" if originalsource == "National Food Balance Sheet"
replace originalsource = "WFP cluster" if originalsource == "Food Procurement Tracking System (FPTS)"
replace originalsource = "WFP cluster" if originalsource == "SPR"
replace originalsource = "" if originalsource == "Household Budget Surveys"

* Health
replace originalsource = "UNAIDS cluster" if originalsource == "UNAIDS"
replace originalsource = "UN cluster" if originalsource == "UNPD/ADB"
replace originalsource = "WHO cluster" if originalsource == "WHO"
replace originalsource = "UN cluster" if originalsource == "UNDP"
replace originalsource = "UN cluster" if originalsource == "UNPD"
replace originalsource = "WHO cluster" if originalsource == "WHO/UNICEF/WB"
replace originalsource = "UN cluster" if originalsource == "UNDP/ADB"
replace originalsource = "UNAIDS cluster" if originalsource == "UNAIDS/WHO"
replace originalsource = "Other" if originalsource == "CIESIN/YCELP"
replace originalsource = "WHO cluster" if originalsource == "PMTCT STAT"
replace originalsource = "UN cluster" if originalsource == "UNDESA"
replace originalsource = "UN cluster" if originalsource == "UNESCO"
replace originalsource = "UN cluster" if originalsource == "UN Maternal Mortality Estimation Group"
replace originalsource = "UN cluster" if originalsource == "UNICEF"
replace originalsource = "Other" if originalsource == "Gallup"
replace originalsource = "UN cluster" if originalsource == "UN-IGME"
replace originalsource = "Other" if originalsource == "International Diabetes Federation"
replace originalsource = "WHO cluster" if originalsource == "WHO/UNICEF/UNFPA/WB/UN"
replace originalsource = "UN cluster" if originalsource == "UNICEF/WHO/WB/UN DESA"
replace originalsource = "WHO cluster" if originalsource == "WHO/Stevens Ga, Finucane MM"
replace originalsource = "Other" if originalsource == "HDDS"
replace originalsource = "National Census and Ministry reporting" if originalsource == "National statistical offices/ministries of agriculture/national institutions"
replace originalsource = "Vital registration" if originalsource == "Vital registration systems/National population censuses/Household surveys/Multi-purpose surveys"
replace originalsource = "Health ministries" if originalsource == "Health ministries"
replace originalsource = "Health ministries" if originalsource == "Health ministries/NTPs"
replace originalsource = "Other" if originalsource == "NTBP"
replace originalsource = "National Census and Ministry reporting" if originalsource == "National Census or statistical offices"
replace originalsource = "Health ministries" if originalsource == "Health facilities"
replace originalsource = "Vital registration" if originalsource == "Civil registration and vital statistics"
replace originalsource = "Vital registration" if originalsource == "Civil registration"
replace originalsource = "Health ministries" if originalsource == "National malaria control programmes/Surveillance systems"
replace originalsource = "Health ministries" if originalsource == "Population-based cancer registries"
replace originalsource = "National Census and Ministry reporting" if originalsource == "National, sub national, or monitoring reports"
replace originalsource = "National Census and Ministry reporting" if originalsource == "Administrative reporting systems"
replace originalsource = "DHS cluster" if originalsource == "DHS"
replace originalsource = "DHS cluster" if originalsource == "DHS/MICS/Other"
replace originalsource = "DHS cluster" if originalsource == "DHS/FHI"
replace originalsource = "Vital registration" if originalsource == "Vital registration systems/national population censuses/household surveys/multi-purpose surveys"
replace originalsource = "Vital registration" if originalsource == "Vital registration systems, household surveys, reproductive age mortality studies, disease surveillance, and national population census"
replace originalsource = "DHS cluster" if originalsource == "National Household Survey/MICS/DHS"
replace originalsource = "DHS cluster" if originalsource == "DHS/FFS/RHS/MICS/other national surveys"
replace originalsource = "DHS cluster" if originalsource == "DHS/RHS/MICS/Civil registration systems"
replace originalsource = "DHS cluster" if originalsource == "DHS/MICS/FFS/RHS"
replace originalsource = "DHS cluster" if originalsource == "DHS/RHS/MICS/PAPFAM/FFS/other national survey"
replace originalsource = "Health ministries" if originalsource == "Population based survey and clinic attendees"
replace originalsource = "DHS cluster" if originalsource == "DHS/MICS"
replace originalsource = "Other" if originalsource == "Compiled by EPSA/PDM/FSOM"
replace originalsource = "WFP cluster" if originalsource == "Compiled by WFP"
replace originalsource = "Other" if originalsource == "SQUEC"
replace originalsource = "WHO cluster" if originalsource == "Compiled by WHO"
replace originalsource = "UN cluster" if originalsource == "Compiled by UN-IGME"
replace originalsource = "Other" if originalsource == "Serosurvey"
replace originalsource = "DHS cluster" if originalsource == "DHS/Other"
replace originalsource = "Health ministries" if originalsource == "National nutrition surveys"
replace originalsource = "Europe cluster" if originalsource == "DANIDA/DAC"
replace originalsource = "WHO cluster" if originalsource == "WHO/UNICEF/UNFPA/WB"
replace originalsource = "UNAIDS cluster" if originalsource == "UNAIDS/UNICEF/WHO"
replace originalsource = "UN cluster" if originalsource == "UNICEF/WHO/WB"
replace originalsource = "UNAIDS cluster" if originalsource == "Vased on UNAIDS"
replace originalsource = "WHO cluster" if originalsource == "Based on WHO"
replace originalsource = "" if originalsource == "Capacity assessment analysis"
replace originalsource = "WFP cluster" if originalsource == "SPR/global nutrition update"
replace originalsource = "WFP cluster" if originalsource == "Food aid providers"
replace originalsource = "" if originalsource == "High quality TB surveillance system"
replace originalsource = "Key informants" if originalsource == "Reports of vaccinations performed by service providers"
replace originalsource = "Key informants" if originalsource == "Active surveillance systems with laboratory confirmation"
replace originalsource = "Key informants" if originalsource == "Routine facility information systems"
replace originalsource = "Vital registration" if originalsource == "ART Register"
replace originalsource = "Health ministries" if originalsource == "Survey/Administrative reporting systems"
replace originalsource = "Key informants" if originalsource == "Key informant survey"

replace originalsource = "FAOSTAT" if originalsource == "FAO/UN"
replace originalsource = "WB cluster" if originalsource == "WB/WDI"
replace originalsource = "National Census and Ministry reporting" if originalsource == "Statistical Report"

